In [ ]:
import numpy as np
from cc_funcs import lambda_to_eta, cc_log_prob, cc_log_norm_const
from cc_samplers import sample_cc_perm, sample_cc_ordered

# Generate example λ values for 10 samples and 4 categories
lam = np.random.rand(10, 4)
lam = lam / np.sum(lam, axis=1, keepdims=True)  # normalize each row to sum to 1

# Permutation-based sampler (Algorithm 2)
samples_perm = sample_cc_perm(lam)
print("Permutation-based samples:")
print(samples_perm)
print("Each sums to:", np.sum(samples_perm, axis=1))

# Ordered rejection sampler (Algorithm 1)
samples_ordered = sample_cc_ordered(lam)
print("Ordered samples:")
print(samples_ordered)
print("Each sums to:", np.sum(samples_ordered, axis=1))


Permutation-based samples:
[[0.52460814 0.1380247  0.12908514]
 [0.17550283 0.37035519 0.01211597]
 [0.38175312 0.35983548 0.18339556]
 [0.03087018 0.21115757 0.36494992]
 [0.25520016 0.55895007 0.01364293]
 [0.30522081 0.0969872  0.15333195]
 [0.1485796  0.16101762 0.35687457]
 [0.3139149  0.1501662  0.45898156]
 [0.04081652 0.65173049 0.14121923]
 [0.21538759 0.10738672 0.07147496]]
Each sums to: [0.79171798 0.557974   0.92498416 0.60697767 0.82779315 0.55553995
 0.66647179 0.92306267 0.83376624 0.39424926]
Ordered samples:
[[0.00331872 0.53344593 0.09792489 0.36531046]
 [0.5428794  0.03939014 0.38808466 0.0296458 ]
 [0.01018889 0.07031562 0.53995926 0.37953622]
 [0.17416029 0.42587649 0.29158066 0.10838255]
 [0.19408585 0.09866941 0.5110284  0.19621634]
 [0.14050926 0.26634134 0.05863151 0.53451789]
 [0.43714391 0.26561579 0.14702314 0.15021715]
 [0.40184755 0.05071518 0.45643075 0.09100652]
 [0.48224081 0.09897295 0.41301644 0.00576979]
 [0.45297569 0.43027535 0.10614661 0.01060234